apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: platform-secrets
  namespace: flux-system
spec:
  interval: 10m
  path: ./gitops/platform/secrets
  prune: true
  wait: true
  dependsOn:
    - name: platform-controllers
  sourceRef:
    kind: OCIRepository
    name: edge-factory
